// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz5AR68jfiTQUK4oQVhTbSreGFzAYCfVg',
    appId: '1:1057474569586:web:1dca612529c7a7787a69eb',
    messagingSenderId: '1057474569586',
    projectId: 'learnquest-e45f3',
    authDomain: 'learnquest-e45f3.firebaseapp.com',
    storageBucket: 'learnquest-e45f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEpXPBy4sqUzhLoKKRl4Q_3oZO3murSSk',
    appId: '1:1057474569586:android:894667d4d9488ff27a69eb',
    messagingSenderId: '1057474569586',
    projectId: 'learnquest-e45f3',
    storageBucket: 'learnquest-e45f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuvFvzeYPcOx8ymvjYmZs3QqhkWy3UhoM',
    appId: '1:1057474569586:ios:81ba727a593d2ff97a69eb',
    messagingSenderId: '1057474569586',
    projectId: 'learnquest-e45f3',
    storageBucket: 'learnquest-e45f3.appspot.com',
    iosBundleId: 'com.example.learnquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuvFvzeYPcOx8ymvjYmZs3QqhkWy3UhoM',
    appId: '1:1057474569586:ios:81ba727a593d2ff97a69eb',
    messagingSenderId: '1057474569586',
    projectId: 'learnquest-e45f3',
    storageBucket: 'learnquest-e45f3.appspot.com',
    iosBundleId: 'com.example.learnquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz5AR68jfiTQUK4oQVhTbSreGFzAYCfVg',
    appId: '1:1057474569586:web:787e5572d332330c7a69eb',
    messagingSenderId: '1057474569586',
    projectId: 'learnquest-e45f3',
    authDomain: 'learnquest-e45f3.firebaseapp.com',
    storageBucket: 'learnquest-e45f3.appspot.com',
  );

}